- name: installer python3-pip
  become: true
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: installer docker et docker-compose en Python
  become: true
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3

- name: lancer le conteneur
  become: true
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started
